### ISSUE TITLE
Guard dependency for 0.3.0

### ISSUE THREAD

**Issue by thibaudgg** [mordaroso/guard-passenger#2]
Hi Fabio,

Can you please udpate the guard dependency to something like guard, '>= 0.2.1' rather than '~> 0.2.1' because it'll not take the new 0.3.0 guard version.

Thanks a lot! 
Thibaud

PS: you can push/pull directly in https://github.com/guard/guard-passenger

**Comment by mordaroso** [comment]
I really think the twiddle wakka is the right way to define dependencies.
It only works if you use the versioning correctly. Are you using the Semantic Versioning for guard?

If so I'll change the dependency to ~> 0.3

**Comment by thibaudgg** [comment]
Yep, I'm using Semantic Versioning for guard.
Versoin 0.3.0 change some Guardfile syntax (regex parsing) so I think a minor version update is appropriate right?

Thank for the dependency change, if guard-passenger is working for you with guard 0.3.0.

**Comment by mordaroso** [comment]
resolved
