### ISSUE TITLE
Passenger starts up ok, but doesn't stop when guard exits

### ISSUE THREAD

**Issue by the-web-dev** [mordaroso/guard-passenger#5]
I noticed this for the first time earlier this month, when I installed guard + passenger on a new computer.

When running older versions, passenger exits correctly when guard is stopped, but upgrading to the latest versions, this is no longer the case.

This set of gems (from an old project) works correctly
- guard (0.8.4)
- guard-bundler (0.1.3)
- guard-livereload (0.3.1)
- guard-passenger (0.3.0)
- passenger (3.0.9)

This set of gems (after updating the project, or starting new) doesn't:
- guard (1.2.1)
- guard-bundler (1.0.0)
- guard-livereload (1.0.0)
- guard-passenger (0.5.0)
- passenger (3.0.13)

**Comment by mordaroso** [comment]
Fixed by #6
